from __future__ import annotations

from pathlib import Path

from docx import Document
from docx.enum.text import WD_BREAK
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.shared import Inches, Pt
from docx.oxml import OxmlElement
from docx.oxml.ns import qn


OUT = Path("reviewer_comments_responses_addressed_so_far_brief.docx")


def set_cell_shading(cell, fill: str) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:fill"), fill)
    tc_pr.append(shd)


def set_cell_text(cell, text: str, bold: bool = False) -> None:
    cell.text = ""
    p = cell.paragraphs[0]
    run = p.add_run(text)
    run.bold = bold
    run.font.size = Pt(9)
    cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER


def add_table(doc: Document, rows: list[tuple[str, str, str, str]]) -> None:
    table = doc.add_table(rows=1, cols=4)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.style = "Table Grid"
    hdr = table.rows[0].cells
    for cell, text in zip(hdr, ["Reviewer", "Comment", "Issue", "Status"]):
        set_cell_text(cell, text, True)
        set_cell_shading(cell, "D9EAF7")
    for reviewer, comment, issue, status in rows:
        cells = table.add_row().cells
        for cell, text in zip(cells, [reviewer, comment, issue, status]):
            set_cell_text(cell, text)


def add_entry(doc: Document, reviewer: str, comment_no: str, comment: str, response: str, updates: str) -> None:
    h = doc.add_heading(f"{reviewer} - Comment {comment_no}", level=2)
    for run in h.runs:
        run.bold = False
    p = doc.add_paragraph()
    p.add_run("Status: ").bold = True
    p.add_run("Addressed in revised manuscript")
    p = doc.add_paragraph()
    p.add_run("Reviewer comment: ").bold = True
    p.add_run(comment)
    p = doc.add_paragraph()
    p.add_run("Response: ").bold = True
    p.add_run(response)
    p = doc.add_paragraph()
    p.add_run("Updates in manuscript: ").bold = True
    p.add_run(updates)


entries = [
    ("R1", "#1", "AI-assisted writing, repetitive transition paragraphs, and technical validation", "Addressed"),
    ("R1", "#2", "Architectural adaptation and LSTM interpretation", "Addressed"),
    ("R1", "#3", "Privacy and memorization risk under conditioning", "Addressed"),
    ("R1", "#4", "Dependency preservation and practical EMS/planning usefulness", "Addressed"),
    ("R1", "#5", "Uniform charging assumption and downstream load-profile validity", "Addressed"),
    ("R1", "#6", "Non-independent repeated seed runs and statistical wording", "Addressed"),
    ("R1", "#7", "Variation among residential location groups", "Addressed"),
    ("R1", "#8", "Physical constraints and charger-feasibility screening", "Addressed"),
    ("R1", "#9", "Justification for 1000 diffusion steps", "Addressed"),
    ("R1", "#10", "Need for tabular diffusion baseline", "Addressed"),
    ("R1", "#11", "Rare charging behaviour and upper-tail fidelity", "Addressed"),
    ("R1", "#12", "Repetitive or low-resolution figures", "Addressed"),
    ("R1", "#13", "Controllable scenario generation wording overstated", "Addressed"),
    ("R1", "#14", "Energy-system analysis claims should be framed as indicative", "Addressed"),
    ("R1", "#15", "Preprocessing exclusions insufficiently detailed", "Addressed"),
    ("R1", "#16", "Computational-cost reporting", "Addressed"),
    ("R1", "#17", "Architecture-selection justification", "Addressed"),
    ("R3", "#1", "Statistical significance and exploratory comparisons", "Addressed"),
    ("R3", "#2", "Hyperparameter, CTGAN, and code-availability documentation", "Addressed"),
    ("R3", "#3", "Split transparency, location-specific results, and monthly case studies", "Addressed"),
    ("R3", "#4", "Load-profile reconstruction sensitivity and peak-metric interpretation", "Addressed"),
    ("R3", "#5", "Frobenius magnitude context and pairwise dependency similarity", "Addressed"),
    ("R3", "#6", "Figure embedding, numbering, and appendix references", "Addressed"),
    ("R3", "#7", "Recent literature coverage", "Addressed"),
    ("R4", "#1", "Need for TabDDPM/tabular diffusion baseline", "Addressed"),
    ("R4", "#2", "Architecture justification and LSTM sequence length", "Addressed"),
    ("R4", "#3", "Rationale for weekday grouping", "Addressed"),
    ("R4", "#4", "Repeated seeds and statistical method", "Addressed"),
    ("R4", "#5", "Construction of residential location groups", "Addressed"),
    ("R4", "#6", "Privacy-preservation claim not formally evaluated", "Addressed"),
    ("R4", "#7", "Monthly case studies and limits of seasonal validation", "Addressed"),
    ("R4", "#8", "Session-level split and possible user overlap", "Addressed"),
]

detailed = [
    ("Reviewer 1", "1",
     "The authors must explicitly state which sections were generated by AI and how they validated the technical accuracy of those portions. The current manuscript shows signs of structural AI-generated text, particularly in the redundant transition paragraphs.",
     "We addressed this by adding a generative-AI declaration and by revising repetitive transition paragraphs throughout the manuscript. The declaration states that AI tools were used for language editing, LaTeX formatting support, code refinement, and consistency checks, and that the authors reviewed all AI-assisted outputs and take responsibility for the manuscript content.",
     "Declaration of generative AI and AI-assisted technologies; Introduction; Related Work; Results and Discussion; Conclusion."),
    ("Reviewer 1", "2",
     "Authors should justify why a recurrent architecture (originally designed for time-series sequences) is used for independent tabular session records. The \"simplified\" use of LSTM as a non-linear transformation layer seems like a retrofitting effort rather than a sound design choice.",
     "We agree with the comment. Section 4.2.2 now clarifies that the sequence length is one, so the LSTM is not used for temporal sequence modelling across sessions. It is retained as a gated nonlinear block from the original DiffCharge denoising architecture to test whether that architecture can be adapted to session-level tabular generation.",
     "Section 4.2.2."),
    ("Reviewer 1", "3",
     "The authors must clarify if the conditioning variables (season, location) were used in a way that allows the model to \"memorize\" specific training samples, given the relatively small dataset size after preprocessing.",
     "We addressed this by removing unsupported privacy-preservation claims and adding a nearest-neighbor memorization diagnostic. The manuscript now states that the diagnostic is only a basic check and not a formal privacy evaluation.",
     "Introduction; Section 5.11; Discussion; Conclusion."),
    ("Reviewer 1", "4",
     "The Frobenius norm results indicate that the models struggle to capture inter-variable dependencies. Authors should provide a quantitative analysis of how the failure to capture these dependencies (e.g., between plug-in hour and connection time) invalidates the usefulness of the synthetic data for real-world EMS planning.",
     "We addressed this by adding location-wise Frobenius results, a real-data baseline for magnitude, and quantitative pairwise two-dimensional distribution similarity. The revised text explains that dependency errors limit use in peak-coincidence, flexibility-window, and charger-control studies without further validation.",
     "Sections 5.6-5.8; Discussion; Conclusion."),
    ("Reviewer 1", "5",
     "The assumption of uniform energy distribution across the connection duration is physically unrealistic. Authors must discuss how this simplification artificially inflates the performance metrics (RMSE/peak errors) and why it should be considered reliable for downstream grid impact studies.",
     "We agree that the original framing was too strong. We added a sensitivity analysis using front-loaded fixed-power reconstruction and now describe the load-profile analysis as indicative rather than a physically resolved grid-impact simulation.",
     "Load-profile methodology; Section 5.10; Discussion; Abstract; Conclusion."),
    ("Reviewer 1", "6",
     "Authors should refrain from labeling differences as \"significant\" when the test observations are not independent. The reliance on the Holm-Bonferroni correction on non-independent samples is a statistical red flag that needs to be addressed.",
     "We addressed this by reframing the Wilcoxon and Holm-Bonferroni results as exploratory matched comparisons. Mean +/- standard deviation is now the primary summary, and the manuscript distinguishes descriptive mean advantages from exploratory statistical evidence.",
     "Abstract; Section 4.6; Section 5.2; Discussion; Conclusion."),
    ("Reviewer 1", "7",
     "The performance variation across location groups is significant. Authors must explain why the model fails to perform consistently and why this is not an indicator of model instability rather than \"contextual sensitivity.\"",
     "We addressed this by reporting location-group-specific performance more prominently and relating the variation to held-out sample size and location-specific connection-time behaviour.",
     "Section 5.5; Discussion; Conclusion."),
    ("Reviewer 1", "8",
     "There is no evidence that the model enforces physical constraints (e.g., realistic power limits for home chargers). Authors must explain how they guarantee that generated sessions do not violate physical charging hardware limits.",
     "We agree that the model does not guarantee charger limits internally. We added a post-generation physical-constraint check for real, diffusion, CTGAN, and TabDDPM samples, including delivered energy and implied average charging power.",
     "Section 4.6; Section 5.12; Discussion."),
    ("Reviewer 1", "9",
     "Authors should perform a sensitivity analysis on the noise schedule hyperparameters (1,000 steps). It is unclear why this specific schedule is optimal for this tabular dataset.",
     "We addressed this by adding a limited diffusion-step sensitivity analysis for 250, 500, and 1000 steps. The manuscript now presents 1000 steps as the best setting among the tested validation runs, not as a globally optimal schedule.",
     "Section 4.2.2; Appendix or Results sensitivity table."),
    ("Reviewer 1", "10",
     "Why was TabDDPM (the state-of-the-art for tabular diffusion) not used as a benchmark? The comparison with CTGAN is insufficient to claim the superiority of the proposed framework.",
     "We addressed this by adding TabDDPM as a same-family tabular diffusion benchmark and reporting it under the same yearly sampling and evaluation setup.",
     "Related Work; Section 4.4; Results; Discussion; Conclusion."),
    ("Reviewer 1", "11",
     "The manuscript fails to demonstrate how the model handles rare charging behaviors (e.g., long-duration sessions). The authors should include a specific analysis of the model's accuracy on the tails of the distribution.",
     "We addressed this by adding an upper-tail bin-frequency analysis for connection time and delivered energy. The revised text reports tail frequencies by location group and model, rather than relying only on full-distribution metrics.",
     "Section 4.6; Section 5.9; Discussion."),
    ("Reviewer 1", "12",
     "Many of the figures in the appendix and main text are repetitive. The authors should consolidate the architecture-level diagnostics into a single, comprehensive comparison.",
     "We addressed this by moving architecture-level diagnostics to the appendix, keeping the cross-location tables as the primary evidence, and regenerating lower-resolution figures at 300 dpi.",
     "Appendices A-C; figure files; main-text cross-references."),
    ("Reviewer 1", "13",
     "The claim that the model provides \"controllable scenario generation\" is overstated. Authors must demonstrate how a user can precisely manipulate the output without retraining the model.",
     "We agree. The manuscript now uses conditional scenario generation instead of controllable scenario generation, because the study demonstrates predefined conditioning variables rather than fine-grained user control.",
     "Abstract; Introduction; Methodology; Discussion; Conclusion."),
    ("Reviewer 1", "14",
     "Authors must qualify the claim that synthetic data is ready for \"energy-system analysis.\" Given the poor dependency preservation, the data should be labeled as \"indicative only\" throughout the abstract and conclusion.",
     "We addressed this by qualifying downstream claims and describing the load-profile analysis as an indicative downstream assessment. The limitations are now linked to dependency preservation and simplified load reconstruction.",
     "Abstract; Results; Discussion; Conclusion."),
    ("Reviewer 1", "15",
     "The exclusion of sessions based on \"implausible or anomalous\" labels in section 3.2 is not sufficiently detailed. Authors must provide the criteria for these exclusions to ensure reproducibility.",
     "We addressed this by adding the preprocessing criteria and sequential removal counts used to obtain the final modelling dataset.",
     "Section 3.2; preprocessing-exclusion table."),
    ("Reviewer 1", "16",
     "Diffusion models are notoriously resource-intensive. Authors must report the training time and inference latency compared to CTGAN to assess the practical trade-off.",
     "We addressed this by adding computational-cost reporting for training time, yearly generation time, throughput, and hardware.",
     "Section 5.3; computational-cost table."),
    ("Reviewer 1", "17",
     "The justification for the selected architecture (3 layers/2 heads) is weak. Provide the validation curves showing the convergence of these specific parameters to justify their optimality.",
     "We addressed this by documenting the architecture-screening setup and moving architecture-level diagnostics to the appendix. The selected architecture is now presented as the best validation-screened configuration within the tested grid.",
     "Section 4.5; Section 5.1; Appendices A and B."),
    ("Reviewer 3", "1",
     "The manuscript makes several claims about statistical significance that are inconsistent with the study's design limitations.",
     "We agree with the comment. The revised manuscript frames p-values as exploratory matched comparisons and avoids treating repeated seed runs within the same location group as independent observations.",
     "Abstract; Section 4.6; Section 5.2; Discussion; Conclusion."),
    ("Reviewer 3", "2",
     "Section 4.2.2 states: \"To study how the network architecture affects performance, different depths were tested and the role of self-attention was explored.\" However, no details are provided on the specific hyperparameter ranges, optimization strategy, epochs, learning rates, batch sizes, early stopping criteria, or validation monitoring. Section 4.3 also gives insufficient detail on the CTGAN architecture and implementation. The manuscript also states that the implementation source code is publicly available on GitHub, but no repository URL is provided.",
     "We addressed this by extending the architecture and benchmark descriptions. Section 4 now documents the diffusion and CTGAN settings, CTGAN self-attention modification, tested depth/head variants, training settings, validation monitoring, and the GitHub URL. A Data and Code Availability statement was also added.",
     "Sections 4.2.2, 4.3, and 4.5; Data and Code Availability."),
    ("Reviewer 3", "3",
     "Table 2 reports full preprocessed counts, while the manuscript also refers to held-out evaluation counts. The reviewer asked for exact train/validation/test sizes, clearer stratification details, and a clearer link between Table 2 and the held-out evaluation subsets. The reviewer also noted that repeated seeds within a location group share the same fixed held-out test set, so location-specific results should be reported because location groups differ in size and characteristics. The reviewer further asked for clarification that the monthly evaluation extracts monthly subsets from yearly generated samples rather than independently generating month-specific samples.",
     "We addressed these points by adding the exact train/validation/test counts, stratification variables, and session-level split description. We also added location-specific results and clarified that January, May, July, and October are monthly case studies extracted from yearly generated samples.",
     "Section 3.2; Sections 5.4-5.5; Discussion; Conclusion."),
    ("Reviewer 3", "4",
     "Section 5.8 states: \"Aggregate load curves were reconstructed by distributing the delivered session energy uniformly across the generated connection duration.\" The reviewer noted that this is a significant limitation for peak-demand analysis, grid impact assessment, and flexibility estimation, and requested a sensitivity analysis or stronger limitation framing.",
     "We addressed this by adding the fixed-power sensitivity analysis and by labelling the load-profile results as indicative. The revised text explains that peak and variability metrics depend on the reconstruction assumption.",
     "Load-profile methodology; Section 5.10; Discussion; Conclusion."),
    ("Reviewer 3", "5",
     "The Frobenius norm scales with the number of variables and the magnitude of associations. Without context on what constitutes a \"meaningful\" difference, this metric is difficult to interpret. The reviewer also requested quantitative pairwise distribution similarity rather than relying only on visual inspection for one location group.",
     "We addressed this by adding Frobenius magnitude context, a real-data location baseline, location-wise Frobenius results, and quantitative pairwise two-dimensional similarity metrics.",
     "Sections 5.6-5.8; Discussion; Conclusion."),
    ("Reviewer 3", "6",
     "The PDF contains placeholder references for figures but the actual figures are embedded as separate files or missing. Some figures are referenced in the text but appear to be numbered inconsistently, and Figures 8-11 appear to be in the appendix.",
     "We addressed this by checking Figures 1-11, correcting appendix references, and regenerating the lower-resolution figure files at 300 dpi. Appendix figures are now referred to as appendix diagnostics rather than main-text figures.",
     "Figures 1-11; Appendices A-C; main-text figure references."),
    ("Reviewer 3", "7",
     "The reviewer requested that recent relevant literature be reviewed and incorporated into the Related Work and comparison/discussion where appropriate.",
     "We addressed this by adding relevant recent EV charging forecasting, planning, and flexibility studies to the Related Work and clarifying how they differ from synthetic session-level data generation.",
     "Section 2."),
    ("Reviewer 4", "1",
     "The compares the proposed diffusion model with CTGAN, but CTGAN is only one benchmark for tabular data generation. The authors are advised to include a more relevant tabular diffusion baseline.",
     "We addressed this by adding TabDDPM as an additional tabular diffusion benchmark and evaluating it under the same yearly sampling and evaluation setup.",
     "Related Work; Section 4.4; Results; Discussion; Conclusion."),
    ("Reviewer 4", "2",
     "The is based on the DiffCharge diffusion model, time-dependent data. However, using an LSTM network with a sequence length of 1 does not reflect the benefits of choosing this architecture. The authors are advised to strengthen the related discussion.",
     "We addressed this by clarifying that the LSTM is not used for temporal sequence modelling when the sequence length is one. The revised text explains its role as an inherited gated nonlinear block from DiffCharge.",
     "Section 4.2.2; Conclusion and future work."),
    ("Reviewer 4", "3",
     "The divides the seven days of the week into four groups: Monday to Thursday, Friday, Saturday, and Sunday. The author advised to strengthen the discussion regarding the rationale behind this classification.",
     "We addressed this by explaining that Monday-Thursday showed similar observed plug-in-hour patterns, while Friday, Saturday, and Sunday were kept separate to preserve weekend-transition behaviour and avoid sparse joint conditioning groups.",
     "Section 3.2."),
    ("Reviewer 4", "4",
     "The uses multiple random seeds and location groups for statistical comparison, but repeated seeds within the same location group share the same test set. Therefore, these results should not be treated as fully independent observations. The authors are advised to adopt a more appropriate statistical method.",
     "We addressed this by treating the statistical tests as exploratory matched comparisons and by using mean +/- standard deviation as the primary summary.",
     "Section 4.6; Section 5.2; Discussion; Conclusion."),
    ("Reviewer 4", "5",
     "The reviewer asked how the residential locations were combined into four location groups and requested the grouping criteria and rationale.",
     "We addressed this by adding the exact location-group construction, the excluded low-sample locations, and the similarity-based grouping rationale. The manuscript now states that the groups are empirical conditioning categories, not geographically contiguous regions.",
     "Section 3.2; location-group construction table."),
    ("Reviewer 4", "6",
     "The paper claims that the proposed method achieves privacy protection, but there is no privacy evaluation anywhere in the paper, so the method's privacy-preserving capability cannot be substantiated.",
     "We agree. Unsupported privacy-preservation claims were removed. The manuscript now states that privacy was not formally evaluated and includes only a basic nearest-neighbor memorization diagnostic.",
     "Introduction; Section 5.11; Discussion; Conclusion."),
    ("Reviewer 4", "7",
     "The seasonal evaluation only considered January and May. The reviewer noted that these two months do not cover summer and autumn and should not be presented as comprehensive seasonal validation without further justification.",
     "We addressed this by reframing the analysis as selected monthly case studies and adding July and October. The manuscript also clarifies that monthly subsets are extracted from yearly generated samples.",
     "Section 4.2.3; Section 5.4; Discussion; Conclusion."),
    ("Reviewer 4", "8",
     "The data already includes a user_id field, but the method used to split the training set is not described. If the same user appears in both the training and test sets, is this evaluation result still valid?",
     "We addressed this by clarifying that the split is session-level, not user-level. The evaluation is therefore a held-out session fidelity assessment within the observed user population, not an unseen-user or unseen-charger generalization experiment.",
     "Section 3.2; Section 4.6; Discussion; Conclusion."),
]


doc = Document()
section = doc.sections[0]
section.top_margin = Inches(0.7)
section.bottom_margin = Inches(0.7)
section.left_margin = Inches(0.75)
section.right_margin = Inches(0.75)

styles = doc.styles
styles["Normal"].font.name = "Arial"
styles["Normal"].font.size = Pt(10)
styles["Heading 1"].font.name = "Arial"
styles["Heading 1"].font.size = Pt(14)
styles["Heading 2"].font.name = "Arial"
styles["Heading 2"].font.size = Pt(11)

title = doc.add_paragraph()
title.style = doc.styles["Title"]
title.add_run("Reviewer Comments and Responses Addressed So Far").bold = True

doc.add_paragraph(
    "Working response document for the revised EV charging synthetic-data manuscript. "
    "Responses have been shortened to identify what was changed and where, while keeping the reviewer comments visible."
)

doc.add_heading("Current Addressed Items", level=1)
add_table(doc, entries)

p = doc.add_paragraph()
p.add_run().add_break(WD_BREAK.PAGE)
doc.add_heading("Detailed Responses", level=1)
for item in detailed:
    add_entry(doc, *item)

doc.save(OUT)
print(OUT.resolve())
